alias dir='ls -lh --color=auto'
alias ll='ls -lh --color=auto'
alias la='ls -lha --color=auto'
alias l='ls -ahlF --color=auto'
alias ls='ls -h --color=auto'
alias ls-l='ls -lh --color=auto'
alias das='dig +short a'
alias dmx='dig +short mx'
alias dix='dig +short -x'
alias o='less'
alias ..='cd ..'
alias ...='cd ../..'
alias cd..='cd ..'
alias rd='rmdir'
alias md='mkdir -p'
alias vi='vi -c ":sy on"'
alias vi='vim -c ":sy on"'